<?php require APPROOT . '/views/inc_home/header.php'; ?>
  












	<!-- Start of some extra features  
		============================================= -->
		<section id="extra-features" class="extra-features-section" style="background-color: #fff;">
			<div class="container">
				<div class="row section-content">
						<h1 class="title deep-black pb40">Terms & Conditions</h1>
					<div class="section-title text-center pb50" style="text-align:left;">
                    <p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Terms and conditions are legal binding&nbsp;to use of our service like Hellowcart Mobile App . Users or visitors of our platform will be pronounced as user or your. Also using the platform, users must agree to our terms and conditions. If any of our terms are not agreeing then your advice is not to use our platform. Also user check our terms and conditions regularly because we may change or update terms any time without any Prior notice.</span></p>
<p><br></p>
<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Our Hellowcart app will be registered under Hellow Cart India Private limited. And registered office in Bangalore. As we connect Restaurant and Restaurant visitors by our unique QR Based menu..Also our app will support self pickup and Delivery. We may charge some fee for our services from the user &nbsp;as for the agreement with the vendor.</span></p>
<p><br></p>
<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">We are working as a bridge to connect both the parties will always try to register a Better Quality Restaurant in our platform to give a better experience to our&nbsp;</span></p>
<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">visitors. Also we request users to know about the restaurant before the order of food from that Restaurant. Restaurants will be solely responsible for the &nbsp;quality of the food. And user Feedback will Be the Most Priority to Registered Restaurant.&nbsp;</span></p>
<p><br></p>
<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">We committed to serving a good and better food experience. If there is any dispute with Restaurant regarding food, users can always reach us so we will solve your issues as soon as possible in a positive way.&nbsp;</span></p>
<p><br></p>
<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">For using our platform user should complete&nbsp;18 year or older than that. We are not asking for any proof of your age but using our platform users are declaring your completed legal age to agree to our terms and&nbsp;conditions. If you&apos;re not complete the legal age kindly doesn&rsquo;t use the platform or use with your guardians those completed 18 years.</span></p>
<p><br></p>
<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Our terms and conditions will be under English language only; presently it&apos;s not available in any other languages. &nbsp;If users do not understand English and use any translator to translate our terms and conditions, we are not responsible for any error in understanding.&nbsp;</span></p>
<p><br></p>
<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">user may view our content as unregistered also but ordering from us users must create an account with Hellowcart platform and verify the details.</span></p>
<p><br></p>
<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Using our services or viewing our content it&apos;s free to use. Users should not copy it for any commercial purpose.&nbsp;</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Hellowcart service is a product of Hellowcart India Pvt Ltd. and, networks, mobile applications, and other services provided by us (collectively, the &ldquo;Service&rdquo;). These Terms of Service are a legally binding contract between you and Hellowcart regarding your use of the service.</span></p>
<p><br></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">by clicking &ldquo;I accept,&rdquo; or by downloading, installing, or otherwise accessing or using the service, you agree that you have read and understood, and, as a terms to your use of our services, you agree to be bound by, the following terms and conditions, including hellowcart privacy policy and any additional terms and policies Hellowcart, may change from time to time (together, these &quot;terms&quot;). if you are not eligible, or if u do not agree to these terms, then you do not have our permission to use the service. your use of the service, and hellowcart provision of the service to you, constitutes an agreement by hellowcart and by you to be bound by these terms.</span></p>
<p><br></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">User&apos;s rights about their personal information collected by the Company&hellip;</span></p>
<p><br></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">All the knowledge provided to the corporate by a User, as well as Sensitive Personal information or data, is voluntary. User has the right to withdraw his/her/its consent at any time, by the terms of this Privacy Policy and also the Terms of Use, however, please note that withdrawal of consent won&apos;t be retroactive.</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Users can access, modify, correct and delete the Personal Information provided by them which has been voluntarily given by the User and collected by the Company following this Privacy Policy and Terms of Use. However, if the User updates his/her information, the Company may keep a copy of the information which User originally provided to the Company in its archives for User documented herein. In case the User seeks to update or correct his/her Personal Information, the User may exercise these rights by emailing the Company at privacy@hellowcart.com and communicating the change(s) for updating the Company&rsquo;s records.</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">In case the User will not provide the information or permission to use of Personal Information or subsequently withdraws his/her permission for usage of the Personal Information so collected, the Hellowcart reserves the right to discontinue or reject the services for which the said information was collected.</span></p>
<h2 dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Security Practices and Procedures</span></h2>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">The Company has adopted reasonable security practices and procedures to include technical, operational, managerial, and physical security control measures to protect personal information from loss, misuse, and unauthorized access, disclosure, modification, and destruction</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">The Company takes adequate measures to ensure that the appropriate third-party security practices and procedures are adopted to ensure the security of personal information by third parties who may transfer User&apos;s sensitive personal data or information</span></p>
<p><br></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">You hereby agree that the Company is not responsible for any interrupted information sent over the Internet, and you hereby release us from any and all claims relating to the use of the information withheld in any unauthorized manner.</span></p>
<p><br></p>
<p><br></p>
<h2 dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13.999999999999998pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Types of Personal Information collected by the Company</span></h2>
<p><br></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">. To access all features and benefits on our app users may first need to create an account on our app. As part of the registration process, we may collect the following personal information from users (hereinafter collectively referred to as &ldquo;User Information&rdquo;):</span></p>
<ul>
<li>Name;</li>
<li>User ID;</li>
<li>Email address;</li>
<li>Address (including country and ZIP/postal code);</li>
<li>Gender;</li>
<li>Age;</li>
<li>Phone Number;</li>
</ul>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">. The term &ldquo;User Information&rdquo; shall also include any such documents uploaded or otherwise provided by Users. We shall also keep the data of calls made for orders, inquiries any related reason it may save in our dashboard of Services.</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;</span></p>
<h1 dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:18pt;font-family:Arial;color:#ff0000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Terms &amp; Conditions</span></h1>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Your use of this app including copying or otherwise collecting them in whole or in part, is prohibited without the express written permission of Hellowcart, except for your personal, non-commercial use</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">All information displayed, transmitted, or shipped in Hellowcart is protected by copyright and other intellectual property laws. All rights in this hellow cart app including copyright, are owned or licensed by HellowCart. This site is independently designed, updated, and maintained by Hellowcart</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">You may not modify, publish, transmit, transfer, sell, reproduce, create, distribute, re-post, display, display, or otherwise use any Content available on the App.</span></p>
<p><br></p>
<h1 dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:18pt;font-family:Arial;color:#ff0000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Ownership of rights</span></h1>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Your use of this Hellowcart app or any of its contents, including copying or otherwise collecting them in whole or in part, is prohibited without the express written permission of Hellowcart except for your personal, non-commercial use. All information displayed, transmitted, or shipped in Hellowcart is protected by copyright and other intellectual property laws. All rights in this Hellowcart app, including copyright, are owned or licensed by HellowCart. This site is independently designed, updated, and maintained by Hellowcart</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">The content is owned by Hellowcart or &nbsp;Hellowcart India Pvt Limited. You should not modify, publish, transmit, transfer, sell, reproduce, create derivative work from, distribute, repost, perform, display, or in any way commercially exploit any of the content available on the Hellowcart app.</span></p>
<p><br></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:18pt;font-family:Arial;color:#ff0000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">CANCELATION AND RESPONSIBILITIES</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">User cancels food:- Once the order is accepted by the Vendor and starts the preparation Then food will not be cancelled. If the user cancels the food there is no Refund will be applicable.&nbsp;</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Vendor cancel the food:-. If the vendor cancels the food may be out of stock or after the closing time. In that case, will reissue a full Refund to a user payment module.</span></p>
<p><br></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">We (hellowcart) cancel the food:- if any uncertain reason we cancel the food also will issue a 100% Refund.</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Delivery boy canceled the food:- If the Delivery boy is unable to reach you or locate the address. After the maximum attempt to deliver still unable to Delivery the food then there is no refund will be applicable. In that case Within 45 Minutes or before the closing of Restaurants (whichever is earlier) collect the same food from the Restaurant.&nbsp;</span></p>
<p><br></p>
<p><br></p>
<p><br></p>
<p><br></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Information, names, services, advertisements, images, and contents are provided &ldquo;as it is&rdquo; on this Hellowcart app Hellowcart India Pvt Ltd expressly disclaims all and any kind of warranties, whether express or implied, including, but not limited to, implied warranties of Vendor Ability and fitness for a particular purpose. The user using the information provided on this Hellowcart app may do so after satisfying them that the same suits their individual requirements.</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Hellowcart uses information voluntarily provided by users to optimize their experience on our app, whether to provide personalized elements on the app or to prepare a better future content base in the interests of our users. However, the information contained on this &nbsp;Hellowcart app is not intended to be, and should not be treated as legal or professional advice. &ldquo;HELLOWCART&rdquo; is a registered trademark. All other trademarks, company names or logos, and product names referred to in this Hellowcart app &nbsp;remain the property of their respective owners.</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">In no event shall Hellowcart be responsible to any person or entity for any loss or damage, whether direct, indirect, incidental, consequential, or otherwise, arising out of access or use or dissemination of information contained on this Hellowcart app , including, but not limited to, loss of profits, data, or damage to the user&rsquo;s computer systems. The information, contents, names, images, etc. may be changed, updated, modified, and/or improved from time to time without any notice.</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Hellowcart will surely make all maximum attempts to eliminate and exclude viruses from this Hellowcart App. However, Hellowcart does not ensure or accept any liability in respect thereof. Parties using this Hellowcart App may take suitable precautions before downloading information.</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">This Disclaimer Clause and any claims arising out of the use of the information from this Hellowcart app shall be governed by the laws of India and only the Courts in Bangalore., and no other Courts, shall have jurisdiction over the same. By accessing this Hellowcart app, the user accepts this.</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Prohibited Use:</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;(a) use Hellowcart Social media including Images or any content for any illegal, misleading, or fraudulent activity, defame, abuse, harass, threaten or do any other activity which infringes the rights of Hellowcart or others, or publish, post, upload, distribute or disseminate any inappropriate, profane, defamatory, infringing, obscene, indecent or unlawful topic, name, material or information or any other content which belongs to another person over which You do not have any right through any bookmark, tag or keyword;</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">(b) Make available, sublicense, otherwise transfer or assign, or otherwise exploit Hellowcart or do anything to interfere with or impair the intended operation of Hellowcart support media.</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;(c) edit, change, prepare any derivative work of or alter in any way any of the Images or content provided on Hellowcart &nbsp;</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">(d) input, upload, transmit or otherwise provide to, or through the Cult Social any information or materials that are in violation of law, injurious, contain, transmit or activate any viruses, malicious or harmful code, or any other similar software or programs, or disrupt or interfere with the security of, or otherwise cause harm to, the Platform, systems resources, accounts, passwords, servers or networks connected to or accessible through the Platform or any affiliated or linked sites;</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;(e) act in a manner intended to exceed any restrictions or limitations outlined in these Terms of Use or the Privacy Policy;</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">(f) impersonate any person or entity, or falsely state or otherwise misrepresent Your affiliation with a person or entity;</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;(g) attempt to gain unauthorized access to any portion or feature of the Platform, any other systems or networks connected to the Platform, or to any of the services offered on or through the Platform, by hacking, password mining, or any other illegitimate means;</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">(h) collect or store data about other Users in connection with the prohibited conduct and activities or conduct/forward surveys, contests, pyramid schemes, or chain letters; and</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;(i) upload any other content which is non-compliant with the Information Technology Act, 2000, rules, guidelines, and regulations made there under, including Rule 3 of the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021, Terms and Policies</span></p>
<p><br></p>
<ul style="margin-top:0;margin-bottom:0;padding-inline-start:48px;">
    <li aria-level="1" dir="ltr" style="list-style-type:disc;font-size:13pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;">
        <p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">General Condition</span></p>
    </li>
</ul>
<p><br></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">The user agreed and accepted that Hellowcart shall not be responsible for:</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">The services or food provided by the Vendor include but are not limited to serving of food Orders matching your requirements and taste;</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">The Vendors services or foods, or services provided by Delivery Partners not being up to user expectations or leading to any loss, harm, or damage to him/her; The availability or unavailability of certain items on the menu;</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">The Vendor serving the incorrect Orders; or liability of foods provided by the Vendor. This all will be Responsible for a particular Vendor or the Delivery partner. Hellow Cart will work as a mediator to smooth the process.</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">The details of the menu and price list available on our Platform concerning restaurant services, goods, or any other services are based on the information provided by the Vendors, and Hellowcart shall not be responsible for any change or cancellation, or unavailability.</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">users and Vendors agree and acknowledge that Hellowcart is not responsible for any liability arising out of delivery services provided by the Delivery Partner to them.</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">users may not be able to avail of Services if their delivery location is outside Hellowcart&rsquo;s current scope of Service Location. Hellowcart will keep the user informed of the same at the time of confirming their Order booking.</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Users should understand that delivery time shown at the time of confirming the Order is an approximate estimate timing only and may vary based on the item they order, peak hour, traffic, rainy, and Vendors. Hellowcart will not be responsible for any delay in the delivery of an Order.</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">user understands that certain Vendors undertake delivery of their Foods to the user and the Vendor may charge the user for such service as a Delivery fee. Hellowcart exercises no control on such delivery services and the same shall be under the control of the Vendor alone and hence all or any disputes arising out of such delivery services shall be between the user and the Vendor alone. Hellowcart shall not be responsible for such delivery services and assumes no liability for disputes arising out of the same.</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">the user&apos;s Order will be only delivered to the address designated by him/her at the time of placing the Order on the Platform. user&rsquo;s Order will be cancelled in the event of any change of the address as informed by the Delivery Partner and the User shall not be entitled to any refund for the same. Delivery of food in the event of a change of the delivery location shall be subject to acceptance by the Delivery Partner or sole discretion of Hellowcart.</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">The user shall undertake to provide adequate directions, information, receive the call of the Delivery person, and authorization to accept delivery. In the event of no delivery due to any act or omission attributable to the user, the goods or services shall be deemed to have been delivered to the user, and all risk and responsibility in relation thereto shall be passed to the user without being entitled to any refund.</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">The user understands that Hellowcart liability ends once the Order has been delivered to him/her, except where the product liability of the Vendor subsists.</span></p>
<p><br></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:18pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">THIRD PARTY API</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp; &nbsp;As we are using third party API in our Hellowcart APP for the use of complete platform for the user for better experience. as we use payment gateway razor pay. So we will be sharing the certainly data to them for the online payment but we will not store any card or payment details of user in our app. for more details about razor pay privacy policy you can check page on&nbsp;</span><a href="https://razorpay.com/privacy" style="text-decoration:none;"><span style="font-size:13pt;font-family:Arial;color:#0000ff;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:underline;-webkit-text-decoration-skip:none;text-decoration-skip-ink:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">https://razorpay.com/privacy</span></a><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">.&nbsp;</span></p>
<p><br></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Also we use Dunzoo API for the Delivery services. We share user name, contact number, email id, complete address and user Latlong.for more details on dunzoo privacy policy you can check dunzoo page on&nbsp;</span><a href="https://www.dunzo.com/privacy" style="text-decoration:none;"><span style="font-size:13pt;font-family:Arial;color:#0000ff;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:underline;-webkit-text-decoration-skip:none;text-decoration-skip-ink:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">https://www.dunzo.com/privacy</span></a><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">.&nbsp;</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">for any point misuse of data from the third party mentioned above or not mentioned any other third party service provider we are not reasonable and more details about the policy can check it from there webpage.</span></p>
<p><br></p>
<h5 dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;TERMS AND CONDITIONS:</span></h5>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">The Vendor concurs that it will consistently consent to every one of the arrangements contained in the &apos;Dealer TERMS AND CONDITIONS&apos; added to this Agreement or as accessible on the Hellowcart app (and as changed occasionally). The Vendor thus concurs that the arrangements of the Vendor Terms and Conditions that administer Confidentiality, Governing Law, Termination, and Dispute Resolution will apply mutatis mutandis to this Agreement.&nbsp;</span></p>
<p><br></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Vendor REPRESENTATIONS AND WARRANTIES&nbsp;</span></p>
<p><br></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">The Vendor thus attempts, certifies, addresses, warrants, and concurs that:&nbsp;</span></p>
<p><br></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">4.1 It is on favorable terms under the laws of its fuse or in the locale where it is an inhabitant and additionally works together and has the full position to go into this Agreement and to play out every one of the commitments hereunder as indicated by the terms about.&nbsp;</span></p>
<p><br></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">4.2 It has full force and position to go into this Agreement and to make any move and execute any records needed by the terms about; and that this Agreement, when gone into has been appropriately approved, has been properly and legitimately executed and conveyed, and is its lawful, substantial, and restricting commitment of the Party, enforceable as per the terms in this regard.&nbsp;</span></p>
<p><br></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">4.3 All assents, endorsements, approvals, orders, enlistments or capabilities of, or with, any court or administrative position or other legislative body having purview over such Party, the shortfall of which would antagonistically influence the legitimate and substantial execution, conveyance, and execution of this Agreement or the records and instruments considered thusly, are set up as required.</span></p>
<h5 dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">SUCCESSORS AND ASSIGNS</span></h5>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">The arrangements of this Agreement will be restricting upon and acclimating to the advantage of the Parties hereto and their individual replacements and allowed appoints and Affiliates. The Vendor will not relegate or in any case move this Agreement or any of its freedoms and commitments hereunder whether in entire or to some extent without the earlier ascent of HELLOWCART INDIA PVT LTD&nbsp;</span></p>
<p><br></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">SEVERABILITY&nbsp;</span></p>
<p><br></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">On the off chance that any arrangement of this Agreement will repudiate or be illicit, invalid or unenforceable under the laws of any state, nation or locale in which this Agreement will be performed or upheld, then, at that point, such negation, wrongdoing, weakness or unenforceability will not nullify the whole Agreement. Such arrangement will be considered to be adjusted to the degree significant to deliver it legitimate, lawful, and enforceable, and on the off chance that no such change will deliver it substantially, lawful and enforceable, the Agreement will be understood as though not containing the arrangement held to be invalid, and the legitimacy, legitimateness, and enforceability of the arrangements or pledges of this Agreement will be unaffected, and the freedoms and commitments of the gatherings will be interpreted and implemented in like manner.</span></p>
<p><br></p>
<p><br></p>
<p><br></p>
<h5 dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">INTELLECTUAL PROPERTY RIGHTS&zwj;</span></h5>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Neither one of the gatherings will utilize the Intellectual Property of the other Party in any way besides as allowed hereinafter. HELLOWCART Intellectual Property: all the protected innovation privileges in or identified with, (a) HELLOWCART portable application, &nbsp;(c) HELLOWCART promoting material, (d) HELLOWCART administrations, (e) all trademarks, brand names, and logos of HELLOWCART card, (f) all information gathered by HELLOWCART waiters will consistently remain exclusively under the responsibility for. HELLOWCART claims all authority to alter the licensed innovation directly at some random time with practically no earlier notification. You recognize that HELLOWCART India Pvt Limited is the sole proprietor of the HELLOWCART Intellectual Property, including its name and logo, and is qualified for show, sublicense, alter, change, or in any case utilize such protected innovation in any capacity and structure or design and all correspondence at its own watchfulness.&nbsp;</span></p>
<p><br></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">HELLOWCART, therefore, awards to you a restricted, non-adaptable, non-selective, non-sublicensable, revocable permission to access and utilize HELLOWCART facilitated Vendor App for inner business purposes insofar as your record with HELLOWCART stays current and dynamic. On the off chance that HELLOWCART gives you a Password to get to the Portal, you are exclusively answerable for securing the Password and for any approved or unapproved utilize made of the Password. The Portal, and all source code, copyrights, and other licensed innovations related therewith, are and will stay the sole and selective property of HELLOWCART. You will cease allowing any outsider to utilize your secret word or in any case access the Portal. HELLOWCART will reserve the privilege to end the permit conceded therefore promptly if you have penetrated any terms or conditions set out in the Agreement or your HELLOWCART account is generally ended under any circumstance.&nbsp;</span></p>
<p><br></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Besides as set out hereinabove, nothing in this will be interpreted as an award to you of any protected innovation privileges, or a permit to utilize such protected innovation freedoms, of HELLOWCART.&nbsp;</span></p>
<p><br></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">The protected innovation privileges are adding material to any HELLOWCART application (electronic or local) that is gotten to on any vendor-claimed equipment.</span></p>
<h5 dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">LIMITATIONS</span></h5>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">You consent to conform to the following terms: vendors make a deal to avoid deciphering, decompiling, dismantling, reproducing, rendering, picking apart, or investigating any of the HELLOWCART framework, including other scholarly properties. You make a deal to avoid utilizing the HELLOWCART framework for some other reason other than for the reason it is provided to you by HELLOWCART. You make a deal to avoid duplicating any piece of HELLOWCART Framework disconnected Hellowcart app, completely or to some extent. You consent to keep ease of use rules imparted to you by the HELLOWCART group verbally or in a composed structure during the establishment of the HELLOWCART framework at your business premises.</span></p>
<p><br></p>
<p><br></p>
<h5 dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">CONFIDENTIAL INFORMATION</span></h5>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Any data that a getting party knows or has the motivation to know (either because such data is checked or in any case recognized by the unveiling party orally or recorded as a hard copy as secret or exclusive, has business esteem, or because it isn&apos;t by and large known in the significant exchange or industry) is &quot;Classified Data&quot; of the uncovering party and will stay the sole property of the revealing party. Such Secret Data incorporates however isn&apos;t restricted to information, data (counting by and by recognizable data), thoughts, materials, particulars, methods, plans, programming, specialized cycles and recipes, source code, item plans, deals, cost, and other unpublished monetary data, item and strategies, promoting incomes, use rates, publicizing connections, projections, showcasing information and other comparative data given by a party. For aversion of uncertainty, Client Information, created/got by shippers, will be considered Private Data of HELLOWCART and Vendors. Each party concurs that it won&apos;t unveil, use, alter, duplicate, recreate or in any case uncover such Private Data to any outsider without the earlier composed endorsement of the revealing party aside from that the getting party will reserve the option to unveil such Classified Data to the degree needed by pertinent law or to the chiefs, officials or representatives of the getting party who have a need to know such Secret Data to play out its commitments under the Arrangement and to the degree such chiefs, officials or workers are dependent upon commitments of classification and non-revelation that are generously like the commitments set out in the Understanding. The forbiddances contained in this Segment won&apos;t matter to data (I) currently legally known to the getting party preceding such divulgence by the unveiling party; (ii) freely created by the getting party without admittance to or utilization of the revealing party&apos;s Private Data; (iii) uncovered in distributed materials; (iv) by and large known to the general population; or (v) legitimately acquired from any outsider. Moreover, a party won&apos;t be considered to have penetrated its commitments under the Consent to the degree Private Data is needed to be unveiled by an administrative position, given that, to the degree legitimately practicable, the getting party exhorts the uncovering party before making such revelation all together that the revealing party might have a problem with such divulgence, make a move to guarantee the secret treatment of the Classified Data, or make such other move as it considers proper to secure the Private Data.</span></p>
<h5 dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">GOVERNING LAW</span></h5>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">This agreement is governed and construed under the Laws of the Union of India. The vendor hereby irrevocably consents to the exclusive jurisdiction Of Bangalore.</span></p>
<h5 dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;LIMITATION OF LIABILITY</span></h5>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">HELLOWCART total risk for all cases (counting claims for repayment of outsider harms) emerging out of the Arrangement, regardless of whether in agreement, misdeed, or if not, won&apos;t surpass the measure of charges paid by you to HELLOWCART under the Understanding during the year going before the date on which the case happened. To the most extreme degree allowed by appropriate law, in no occasion will HELLOWCART be obligated for any deficiency of business benefits, business interference, loss of information or any exceptional, roundabout, commendable, coincidental, or important harms emerging from or comparable to the Understanding or the utilization of the Administrations, but caused and paying little heed to the hypothesis of risk. What&apos;s more, HELLO CART won&apos;t be at risk for harm (physical or in any case) caused by you upon any resource or property from the establishment or expulsion of any HELLOWCART item or extra coming up and won&apos;t be liable for substitution or cost of the fix if harms happen. This constraint will apply regardless of whether such harms were predictable and you have been instructed or known concerning the chance of such harms.</span></p>
<h5 dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">CAMPAIGN TERMS OF USE</span></h5>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">The accompanying terms will, notwithstanding each of the different terms set out in this Understanding, oversee your utilization of HELLOWCART&apos;s &quot;Advertising Effort&quot; stage (the &quot;Promoting Lobby Stage&quot;), which, at an overall level, permits you to speak with HELLOWCART individuals.</span></p>
<h5 dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">GENERAL RULES -&nbsp;</span></h5>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">You will, as a condition to utilizing the Promoting Lobby Stage, be needed to observe these guidelines:&nbsp;</span></p>
<p><br></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">1. You will not send Spam! While you are liable for making yourself mindful of a current enemy of SPAM and comparable guidelines that might be in actuality now and again when in doubt, you ought to expect to be that on the off chance that you send individuals to mass email without their consent, you&apos;re spamming.&nbsp;</span></p>
<p><br></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">2. You will not abuse HELLOWCART Adequate Use rules, set up beneath, as it could be basically occasionally, which is essential for this Understanding. On the off chance that you disregard any of these standards, HELLOWCART, notwithstanding whatever other cures that HELLOWCART might have hereunder or in any case, may suspend or end your record.&nbsp;</span></p>
<p><br></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">3. HELLOWCART consents to the current TRAI guidelines (Telecom Administrative Authority of India Act, 1997), and by no means will it abuse any of the relevant guidelines concerning Dealer correspondence.&nbsp;</span></p>
<p><br></p>
<p><br></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Vendor and HELLOWCART are self-employed entities, and no office, association, joint endeavour, representative business, or franchisor-franchisee relationship is planned or made by this Understanding. Each Party will be answerable for the satisfaction of their separate risk to their Vendors or workers and this agreement is no chance permits the one party&apos;s sellers or representatives to raise any case against the other Party. It is explicitly recognized and concurred that HELLOWCART is just giving innovation benefits hereunder and isn&apos;t giving, overseeing, or managing in the issuance of the board of some other merchandise, administrations, or prepaid instalment instrument. Any enrolments and consistency needed under material law for the issuance and the board of prepaid instalment instruments have been/will be acquired by the Vendor, as might be relevant.&nbsp;</span></p>
<p><br></p>
<p><br></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Agreements are lawful restricting to the utilization of our Hellowcart Application . Clients or guests of our platform will be articulated as a user or your. Likewise utilizing the stage, clients should consent to our agreements. On the off chance that any of our terms are not concurring, your recommendation isn&apos;t to utilize our platform. Likewise, users check our agreements consistently in light of the fact that we might change or refresh terms any time with practically no Earlier notification.&nbsp;</span></p>
<p><br></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Our Hellowcart application will be enrolled under Hellow Cart India Private Limited. What&apos;s the more, enlisted office in Bangalore.. Also, our application will uphold self-pickup and Conveyance. We might charge some expense for our dashboard from the client concerning the concurrence with the Vendor.&nbsp;</span></p>
<p><br></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">We are filling in as an extension to associate both the gatherings will consistently attempt to enlist a Superior Quality Restuarants in our platform to give a superior encounter to our&nbsp;</span></p>
<p><br></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">guests. Likewise, we demand clients to think about the Restaurants before the request for food from that Eatery. Restaurants will be exclusively liable for the nature of the food. What&apos;s more, client Input will Be the Most needed to Enlisted Restaurants.&nbsp;</span></p>
<p><br></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">We focused on serving a decent and better food experience. In case there is any question with Restaurants in regards to food, clients can generally contact us so we will tackle your issues straightaway decidedly.&nbsp;</span></p>
<p><br></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">For utilizing our platform clients should finish long-term or be more established than that. We are not requesting any verification of your age however utilizing our platform clients are announcing your finished legitimate age to consent to our terms and conditions. If you&apos;re not finished the lawful age compassionately don&apos;t utilize the stage or use with your gatekeepers those finished 18 years.&nbsp;</span></p>
<p><br></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Our agreements will be under the English language just; by and by it&apos;s not accessible in some other dialects. On the off chance that clients don&apos;t get English and utilize any interpreter to decipher our agreements, we are not liable for any mistake incomprehension.&nbsp;</span></p>
<p><br></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">users may see our substance as unregistered additionally however requesting from us clients should make a record with Hellowcart stage and check the subtleties.&nbsp;</span></p>
<p><br></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Arial;color:#0e101a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Utilizing our administrations or reviewing our substance it&apos;s allowed to utilize. Clients ought not to duplicate it for any business reason.</span></p>
<p><br></p>
<p><br></p>
					</div>
	
				</div><!-- /row -->
			</div><!-- /container -->
		</section>
	<!-- End of some extra features   
		============================================= -->




<?php require APPROOT . '/views/inc_home/footer.php'; ?>